name: DangerousCaves
version: ${version}.${sub-version}
config-version: ${cfg-version}
main: me.imdanix.caves.DangerousCaves
api-version: "1.13"
authors: [imDaniX, Evil-Lootlye]
description: ${description}
softdepend: [PlaceholderAPI, WorldGuard, GriefPrevention, GriefPreventionFlags, Lands]
commands:
  dangerouscaves:
    aliases: [dcaves]
    usage: "/<command> [info|summon|kill|tick|reload]"
    permission: dangerous.caves.command