name: DangerousCaves
version: '${version}.${project.subversion}'
config-version: ${config.version}
main: me.imdanix.caves.DangerousCaves
api-version: '1.13'
authors: [imDaniX, Evil-Lootlye]
description: '${description}'
softdepend: [PlaceholderAPI, WorldGuard, GriefPrevention, GriefPreventionFlags, Lands]
commands:
  dangerouscaves:
    aliases: [dcaves]
    usage: '/<command> [summon|kill|tick|reload]'
    permission: dangerouscaves.command